version: '3.9'

services:
  fastapi_service:
    build:
      context: ./api
      dockerfile: Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
    depends_on:
      - db_postgres
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./api:/home/app
    networks:
      - my-net

  db_postgres:
    image: postgres:15
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./scripts/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    networks:
      - my-net

volumes:
  db-postgres:
    driver: local

networks:
  my-net:
    external: true